### ISSUE TITLE
Issue with our project

### ISSUE THREAD

**Issue by varghese-ascalonic** [apoorva-sharma/deep-frame-interpolation#1]
Hi,
We are doing a project on your project : "Convolutional Neural Networks for Video Frame Interpolation". It is a wonderful paper. So impressive! Pwoli! We have some doubts. You got a deatailed report? Can you please send us the data flow diagram?

For further info, contact : Arun Baby, +91 9495900950.

**Comment by apoorva-sharma** [comment]
Thanks for the interest Arun. I would suggest you take a look at our follow-up report here: http://cs231n.stanford.edu/reports/2017/pdfs/317.pdf

The code for this follow-up project is cleaner than this repository as well, you can find it here https://github.com/apoorva-sharma/finn

Unfortunately, everyone who worked on this project is now busy working on other endeavors, and we don't have the time to maintain the codebase and address any issues you may find. Hopefully the code will give you a good place to start experimenting. 

Best,
Apoorva
